name: Sync Fork

on:
  schedule:
    - cron: 0,30 13,14 * * *
  workflow_dispatch:  # on button click
  
jobs:
  sync:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Fork Sync Upstream
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.SYNC_FORK }}
          upstream_sync_repo: julien-klaus/vorkurs_informatik
          upstream_sync_branch: master

          test_mode: false
          
      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."
    
      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."
