name: Sync Fork

on:
  schedule:
    - cron: 0,30 10,11 * * *
  workflow_dispatch:  # on button click
  
jobs:
  sync:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Sync Upstream
        run: | 
          git remote add -f upstream "https://github.com/julien-klaus/vorkurs_informatik.git"
          git remote -v
          git branch --all
          git config --list
          git fetch
          git checkout master
          git merge --ff-only upstream/master
          git push
