name: Sync Fork

on:
  schedule:
    - cron: 0,30 10,11 * * *
  workflow_dispatch:  # on button click
  
jobs:
  sync:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync Upstream
        run: | 
          git remote add -f upstream "https://github.com/julien-klaus/vorkurs_informatik.git"
          git remote -v
          git checkout master
          git merge upstream/master --allow-unrelated-histories
          git diff-index --quiet HEAD || git push
